import type { SchoolDataExportPayload } from '../school-data-collector.service';

export function buildExportReadme(payload: SchoolDataExportPayload): string {
  return [
    'Alma School Data Export',
    '=======================',
    '',
    `Exported at: ${payload.metadata.exportedAt}`,
    `Scope: ${payload.metadata.scope}`,
    `Tenant: ${payload.metadata.tenantId}`,
    '',
    'WHAT IS IN THIS ZIP',
    '-------------------',
    '1. school-data.json.enc      - Your school data (AES-256-GCM encrypted JSON)',
    '2. school-data.json.enc.meta - Salt, IV, and parameters needed to decrypt',
    '3. README.txt                - This file',
    '',
    'The ZIP itself is also password-protected (same password you chose at export).',
    '',
    'STEP 1 — OPEN THE ZIP',
    '---------------------',
    'Use 7-Zip, WinRAR, or Windows Explorer. Enter the BACKUP PASSWORD you set',
    'when you clicked Export (not your Alma login password).',
    '',
    'STEP 2 — DECRYPT school-data.json.enc',
    '--------------------------------------',
    'You need Node.js installed. From the folder containing the two .enc files, run:',
    '',
    '  node path/to/decrypt-school-export.mjs',
    '',
    'The script is in the Alma repo: backend/scripts/decrypt-school-export.mjs',
    'Copy it next to your extracted files, or pass paths as arguments:',
    '',
    '  node decrypt-school-export.mjs school-data.json.enc school-data.json.enc.meta output.json',
    '',
    'You will be prompted for the same BACKUP PASSWORD.',
    '',
    'Technical details (for custom tooling):',
    '  - Key: PBKDF2-HMAC-SHA256, 210000 iterations, 32-byte key',
    '  - Cipher: AES-256-GCM',
    '  - Read salt, iv, authTag from school-data.json.enc.meta (base64)',
    '',
    'SECURITY',
    '--------',
    'Do not upload this archive to public cloud storage or email it.',
    'Store offline in a secure location. Alma cannot recover your backup password.',
    '',
  ].join('\n');
}
