import type { AccessGate, DashboardWidgetDep, DependencyGraph, ModuleMetrics } from '../types';
import { getModuleEdges } from '../graph/build-graph';
import { mermaidId, titleCase } from '../utils';

const AUTO_HEADER =
  '<!-- AUTO-GENERATED by scripts/generate-module-deps — do not edit -->\n\n';

function formatLayer(layer: string): string {
  const map: Record<string, string> = {
    'backend-module': 'BE module',
    'backend-service': 'BE service',
    'frontend-hook': 'FE hook',
    'frontend-feature': 'FE feature',
    'frontend-nav': 'FE nav',
    database: 'DB',
  };
  return map[layer] ?? layer;
}

function buildTroubleshooting(
  slug: string,
  metrics: ModuleMetrics,
  gates: AccessGate[],
  widgets: DashboardWidgetDep[],
): string {
  const rows: string[][] = [];

  if (slug === 'dashboard') {
    rows.push(
      ['Entire dashboard blank', 'Auth or branch context missing', '`useAuth`, `X-Branch-Id`, `dashboard.controller.ts` guards'],
      ['Single widget empty or error', 'Upstream module API failure', 'Widget component hook + depended module page'],
      ['Low stock widget missing', 'Plan feature gate', '`useSubscriptionFeatures`, `uniforms` module'],
      ['Wrong widgets for role', 'Role widget mapping', '`ROLE_WIDGETS` in `dashboard.service.ts`'],
      ['Preferences not saving', 'Dashboard DB or branch scope', '`dashboard_preferences` table, PUT `/api/v1/dashboard/preferences`'],
    );
  } else if (metrics.moduleType === 'hub') {
    rows.push(
      ['Many features broken after change', 'High fan-in hub — wide blast radius', `Inbound dependents; blast radius: ${metrics.blastRadius}`],
      ['API returns 403', 'RBAC or plan gate', 'Access gates section + `role_permissions` matrix'],
    );
  } else if (gates.some((g) => g.gateType === 'plan')) {
    rows.push(
      ['Feature locked or 403', 'Subscription plan missing feature', '`FeatureAccessGuard`, `useSubscriptionFeatures()`'],
      ['Nav item dimmed/disabled', 'Plan gate on sidebar', '`Sidebar.tsx` subscriptionNavFeatures'],
    );
  } else {
    rows.push(
      ['API 401/403', 'Auth, branch, or permission gate', 'Controller guards + `ensureFeatureEditAccess`'],
      ['Empty list or wrong branch data', 'Missing branch_id filter', 'Service `.eq(\'branch_id\', branchId)`'],
      ['Frontend not loading data', 'Hook or API mismatch', '`frontend/src/hooks/` + Network tab'],
    );
  }

  if (widgets.length > 0) {
    rows.push(['Dashboard widget broken', 'Indirect dependency via dashboard', 'Dashboard module widgets table']);
  }

  const header = '| Symptom | Likely cause | Check first |\n|---------|--------------|-------------|\n';
  return header + rows.map((r) => `| ${r.join(' | ')} |`).join('\n');
}

function buildMermaidSubgraph(slug: string, outbound: string[]): string {
  if (outbound.length === 0) return '_No outbound module dependencies._';

  const lines = ['```mermaid', 'graph LR'];
  const fromId = mermaidId(slug);
  lines.push(`  ${fromId}["${slug}"]`);

  const shown = outbound.slice(0, 15);
  for (const to of shown) {
    lines.push(`  ${fromId} --> ${mermaidId(to)}["${to}"]`);
  }
  if (outbound.length > 15) {
    lines.push(`  ${fromId} --> more["+${outbound.length - 15} more"]`);
  }
  lines.push('```');
  return lines.join('\n');
}

export function renderModulePage(
  graph: DependencyGraph,
  metrics: ModuleMetrics,
): string {
  const slug = metrics.slug;
  const info = graph.modules.get(slug);
  const { outbound, inbound } = getModuleEdges(graph, slug);

  const outboundTargets = [...new Set(outbound.map((e) => e.to))].sort();

  const moduleGates = graph.gates.filter(
    (g) =>
      g.appliesTo.includes(slug) ||
      g.sourceFile.includes(`modules/${slug}/`) ||
      (slug === 'dashboard' && g.gateType === 'widget-role'),
  );

  const tables = graph.tables.filter((t) => t.moduleSlug === slug);
  const widgets = slug === 'dashboard' ? graph.widgets : [];
  const anomalies = graph.anomalies.filter((a) => a.moduleSlug === slug);

  const typeLabel =
    metrics.moduleType.charAt(0).toUpperCase() + metrics.moduleType.slice(1);

  let desc = '';
  if (metrics.moduleType === 'aggregator') {
    desc = '> **Aggregator module** — composes multiple other modules (often via frontend widgets/hooks).\n\n';
  } else if (metrics.moduleType === 'hub') {
    desc = '> **Hub module** — many other modules depend on this. Changes here have wide impact.\n\n';
  } else if (metrics.moduleType === 'leaf') {
    desc = '> **Leaf module** — minimal outbound dependencies at module-import level.\n\n';
  }

  let md = AUTO_HEADER;
  md += `# ${titleCase(slug)}\n\n`;
  md += desc;

  md += `## Dependency summary\n\n`;
  md += `| Fan-out | Fan-in | Hub rank | Blast radius | Dependency rate | Type |\n`;
  md += `|---------|--------|----------|--------------|-----------------|------|\n`;
  md += `| ${metrics.fanOut} | ${metrics.fanIn} | ${metrics.hubRank}/${metrics.totalModules} | ${metrics.blastRadius} | ${metrics.dependencyRate}% | ${typeLabel} |\n\n`;

  if (info?.backendModuleFile) {
    md += `- **Backend module:** \`${info.backendModuleFile}\`\n`;
  }
  if (info?.frontendFeatureFolder) {
    md += `- **Frontend feature:** \`${info.frontendFeatureFolder}\`\n`;
  }
  md += `- **Category:** ${info?.category ?? 'Other'}\n\n`;

  md += `## Depends on (outbound)\n\n`;
  if (outbound.length === 0) {
    md += `_No outbound dependencies detected._\n\n`;
  } else {
    const grouped = new Map<string, { layers: Set<string>; vias: Set<string>; conditions: Set<string> }>();
    for (const e of outbound) {
      if (!grouped.has(e.to)) {
        grouped.set(e.to, { layers: new Set(), vias: new Set(), conditions: new Set() });
      }
      const g = grouped.get(e.to)!;
      g.layers.add(formatLayer(e.layer));
      if (e.via) g.vias.add(e.via);
      if (e.condition) g.conditions.add(e.condition);
    }
    md += `| Module | Layer | Via | Condition |\n|--------|-------|-----|----------|\n`;
    for (const [to, g] of [...grouped.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
      md += `| ${to} | ${[...g.layers].join(', ')} | ${[...g.vias].slice(0, 2).join('; ') || '—'} | ${[...g.conditions].join('; ') || '—'} |\n`;
    }
    md += '\n';
  }

  md += `## Depended on by (inbound)\n\n`;
  if (inbound.length === 0) {
    md += `_No inbound dependencies detected._\n\n`;
  } else {
    md += `| Consumer | Layer | Via | Condition |\n|----------|-------|-----|----------|\n`;
    for (const e of inbound.sort((a, b) => a.from.localeCompare(b.from))) {
      md += `| ${e.from} | ${formatLayer(e.layer)} | ${e.via ?? '—'} | ${e.condition ?? '—'} |\n`;
    }
    md += '\n';
  }

  if (widgets.length > 0) {
    md += `## Dashboard widgets\n\n`;
    md += `| Widget | Hooks | Backend modules | Gates |\n|--------|-------|-----------------|-------|\n`;
    for (const w of widgets) {
      md += `| \`${w.widgetId}\` | ${w.hooks.join(', ') || '—'} | ${w.backendModules.join(', ') || '—'} | ${w.gates.join('; ') || '—'} |\n`;
    }
    md += '\n';
  }

  md += `## Access gates\n\n`;
  if (moduleGates.length === 0) {
    md += `_No specific gates detected — may inherit default JWT + Branch guards._\n\n`;
  } else {
    md += `| Gate type | Condition | Applies to | Source |\n|-----------|-----------|------------|--------|\n`;
    for (const g of moduleGates) {
      md += `| ${g.gateType} | ${g.condition} | ${g.appliesTo} | \`${g.sourceFile}\` |\n`;
    }
    md += '\n';
  }

  md += `## Database tables\n\n`;
  if (tables.length === 0) {
    md += `_No \`.from()\` table references found in this module's services/controllers._\n\n`;
  } else {
    md += `| Table | Source file |\n|-------|-------------|\n`;
    for (const t of tables) {
      md += `| \`${t.table}\` | \`${t.sourceFile}\` |\n`;
    }
    md += '\n';
  }

  if (anomalies.length > 0) {
    md += `## Known anomalies\n\n`;
    md += `| Kind | Detail | Source |\n|------|--------|--------|\n`;
    for (const a of anomalies) {
      md += `| ${a.kind} | ${a.detail} | ${a.sourceFile ?? '—'} |\n`;
    }
    md += '\n';
  }

  md += `## Troubleshooting\n\n`;
  md += buildTroubleshooting(slug, metrics, moduleGates, widgets);
  md += '\n\n';

  md += `## Dependency graph\n\n`;
  md += buildMermaidSubgraph(slug, outboundTargets);
  md += '\n';

  return md;
}
