import type { DependencyGraph, ModuleMetrics, WiringAnomaly } from '../types';
import { getTopAggregators, getTopHubs, getPlanGatedModules } from '../graph/metrics';
import { MODULE_CATEGORIES, mermaidId, titleCase } from '../utils';

const AUTO_HEADER =
  '<!-- AUTO-GENERATED by scripts/generate-module-deps — do not edit -->\n\n';

function buildEcosystemMermaid(topHubs: ModuleMetrics[]): string {
  const lines = ['```mermaid', 'graph TB'];

  const categoryGroups = new Map<string, string[]>();
  for (const [slug, cat] of Object.entries(MODULE_CATEGORIES)) {
    if (!categoryGroups.has(cat)) categoryGroups.set(cat, []);
    categoryGroups.get(cat)!.push(slug);
  }

  let groupIdx = 0;
  for (const [cat, slugs] of categoryGroups) {
    const gid = `g${groupIdx++}`;
    lines.push(`  subgraph ${gid} ["${cat}"]`);
    for (const slug of slugs.slice(0, 8)) {
      lines.push(`    ${mermaidId(slug)}["${slug}"]`);
    }
    lines.push('  end');
  }

  // Show top hub edges
  const hubSlugs = topHubs.slice(0, 5).map((h) => h.slug);
  for (const hub of hubSlugs) {
    for (const e of topHubs) {
      if (e.slug === hub) continue;
    }
  }

  // Connect top 3 hubs to sample dependents from graph
  lines.push('```');
  return lines.join('\n');
}

function buildHubMermaid(hubs: ModuleMetrics[]): string {
  const lines = ['```mermaid', 'graph LR'];
  for (const h of hubs.slice(0, 8)) {
    lines.push(`  ${mermaidId(h.slug)}["${h.slug}<br/>fan-in: ${h.fanIn}"]`);
  }
  lines.push('```');
  return lines.join('\n');
}

export function renderIndex(
  graph: DependencyGraph,
  metrics: Map<string, ModuleMetrics>,
  generatedAt: string,
): string {
  const topHubs = getTopHubs(metrics, 10);
  const topAggregators = getTopAggregators(metrics, 10);
  const planGated = getPlanGatedModules(graph);
  const allSlugs = [...metrics.keys()].sort();

  let md = AUTO_HEADER;
  md += `# Module Dependency Atlas\n\n`;
  md += `Auto-generated full-stack dependency report for NTG Alma.\n\n`;
  md += `**Generated:** ${generatedAt}\n\n`;
  md += `**Regenerate:** \`npm run docs:module-deps\`\n\n`;

  md += `## How to read this report\n\n`;
  md += `| Metric | Meaning |\n|--------|--------|\n`;
  md += `| **Fan-out** | Distinct modules this module depends on |\n`;
  md += `| **Fan-in** | Modules/features that depend on this one |\n`;
  md += `| **Hub rank** | 1 = most depended-on module |\n`;
  md += `| **Blast radius** | Transitive dependents within 3 hops |\n`;
  md += `| **Dependency rate** | \`(fan-in + fan-out) / total modules × 100\` |\n`;
  md += `| **Leaf** | No outbound deps at import level |\n`;
  md += `| **Hub** | Fan-in ≥ 10 |\n`;
  md += `| **Aggregator** | High frontend composition, low backend imports (e.g. Dashboard) |\n\n`;

  md += `## Dependency layers\n\n`;
  md += `\`\`\`mermaid\nflowchart TB\n  subgraph fe [Frontend]\n    Route[App routes]\n    Feature[Feature components]\n    Hook[React Query hooks]\n  end\n  subgraph be [Backend]\n    Controller[Controllers + Guards]\n    Service[Services + DI]\n    Module[NestJS modules]\n  end\n  subgraph db [Database]\n    Tables[PostgreSQL tables]\n  end\n  Route --> Feature --> Hook --> Controller --> Service --> Module\n  Service --> Tables\n\`\`\`\n\n`;

  md += `## Top 10 hubs (highest fan-in)\n\n`;
  md += `| Rank | Module | Fan-in | Fan-out | Blast radius | Type |\n|------|--------|--------|---------|--------------|------|\n`;
  topHubs.forEach((h, i) => {
    md += `| ${i + 1} | [${titleCase(h.slug)}](./modules/${h.slug}.md) | ${h.fanIn} | ${h.fanOut} | ${h.blastRadius} | ${h.moduleType} |\n`;
  });
  md += '\n';

  md += buildHubMermaid(topHubs);
  md += '\n\n';

  md += `## Top aggregators (high frontend composition)\n\n`;
  md += `| Module | Fan-out | Frontend fan-out | Backend fan-out | Type |\n|--------|---------|------------------|-----------------|------|\n`;
  for (const a of topAggregators) {
    md += `| [${titleCase(a.slug)}](./modules/${a.slug}.md) | ${a.fanOut} | ${a.frontendFanOut} | ${a.backendFanOut} | ${a.moduleType} |\n`;
  }
  md += '\n';

  md += `## Plan-gated modules\n\n`;
  md += `These modules require subscription plan features (\`FeatureAccessGuard\` / sidebar \`planLocked\`):\n\n`;
  for (const slug of planGated) {
    md += `- [${titleCase(slug)}](./modules/${slug}.md)\n`;
  }
  md += '\n';

  md += `## Known anomalies\n\n`;
  const globalAnomalies = graph.anomalies;
  if (globalAnomalies.length === 0) {
    md += `_None detected._\n\n`;
  } else {
    md += `| Module | Kind | Detail |\n|--------|------|--------|\n`;
    for (const a of globalAnomalies) {
      md += `| ${a.moduleSlug} | ${a.kind} | ${a.detail} |\n`;
    }
    md += '\n';
  }

  md += `## Ecosystem overview\n\n`;
  md += buildEcosystemMermaid(topHubs);
  md += '\n\n';

  md += `## Module index\n\n`;
  md += `| Module | Category | Fan-in | Fan-out | Rate | Detail |\n|--------|----------|--------|---------|------|--------|\n`;
  for (const slug of allSlugs) {
    const m = metrics.get(slug);
    if (!m) continue;
    const cat = graph.modules.get(slug)?.category ?? 'Other';
    md += `| ${titleCase(slug)} | ${cat} | ${m.fanIn} | ${m.fanOut} | ${m.dependencyRate}% | [View](./modules/${slug}.md) |\n`;
  }
  md += '\n';

  md += `## Quick debugging guide\n\n`;
  md += `1. **Dashboard widget broken** → open [Dashboard](./modules/dashboard.md), find widget row, jump to backend module page.\n`;
  md += `2. **403 on API** → check module's Access gates; verify RBAC matrix or plan feature.\n`;
  md += `3. **Blank nav item** → \`navFeatureMap.ts\` + \`Sidebar.tsx\` plan gates.\n`;
  md += `4. **Hub module regression** → check Top hubs table for blast radius before deploying.\n`;
  md += `5. **Data missing** → module Database tables section + branch_id filtering in service.\n`;

  return md;
}

export function renderGraphJson(
  graph: DependencyGraph,
  metrics: Map<string, ModuleMetrics>,
): string {
  return JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      modules: [...graph.modules.entries()].map(([slug, info]) => ({
        slug,
        ...info,
        metrics: metrics.get(slug),
      })),
      edges: graph.edges,
      gates: graph.gates,
      tables: graph.tables,
      widgets: graph.widgets,
      anomalies: graph.anomalies,
    },
    null,
    2,
  );
}
