export const plans = [
    {
      name: 'Free',
      price: '$0',
      priceNote: '',
      locations: '1',
      users: '2',
      menuItems: '10',
      ordersMonth: '50',
      features: [
        'Point of Sale',
        'Menu & Categories',
        'Order Management',
        'Cash & Card Payments',
        'Customer Records',
        'Dashboard',
        'Multi-language Interface (Arabic, English)',
      ],
      popular: false,
    },
    {
      name: 'Starter',
      price: '$30',
      priceNote: '/month',
      locations: '1',
      users: '5',
      menuItems: '25',
      ordersMonth: '3,000',
      features: [
        'All Free features',
        'Report & Analytics',
      ],
      popular: false,
    },
    {
      name: 'Pro',
      price: '$100',
      priceNote: '/month',
      locations: '5',
      users: '30',
      menuItems: 'Unlimited',
      ordersMonth: '15,000',
      features: [
        'All Starter features',
        'Multi-location',
        'Inventory',
        'AI Features',
      ],
      popular: true,
    },
    {
      name: 'Enterprise',
      price: 'Custom',
      priceNote: '',
      locations: 'Unlimited',
      users: 'Unlimited',
      menuItems: 'Unlimited',
      ordersMonth: 'Unlimited',
      features: [
        'All Pro features',
        'White-label',
        'SLA',
        'API Integrations',
        'Phone support',
      ],
      popular: false,
    },
  ];