/** Tables exported with branch_id filter (explicit list for Phase 1). */
export const BRANCH_SCOPED_TABLES: readonly string[] = [
  'academic_years',
  'subjects',
  'classes',
  'sections',
  'levels',
  'school_days',
  'timing_templates',
  'timing_template_slots',
  'class_timing_assignments',
  'public_holidays',
  'vacations',
  'assessment_types',
  'grade_templates',
  'class_grade_assignments',
  'leave_settings',
  'system_settings',
  'students',
  'staff',
  'class_sections',
  'teacher_assignments',
  'attendance',
  'notifications',
  'leave_requests',
  'early_departure_requests',
  'timetable_slots',
  'subject_templates',
  'subject_template_subjects',
  'class_subject_template_assignments',
  'level_subject_template_assignments',
  'student_subject_template_assignments',
  'assessments',
  'assessment_attachments',
  'student_grades',
  'events',
  'event_participants',
  'event_consents',
  'student_assessment_statuses',
  'behavioral_assessments',
  'behavioral_scores',
  'conversations',
  'conversation_cleared',
  'conversation_hidden',
  'library_items',
  'uniform_items',
  'uniform_stock',
  'uniform_requests',
  'uniform_issuances',
  'result_cards',
  'result_card_deliveries',
  'result_report_settings',
  'student_enrolments',
  'student_promotion_decisions',
  'academic_year_rollovers',
  'fee_templates',
  'fee_template_metrics',
  'fee_template_assignments',
  'fee_student_template_links',
  'fee_metric_exclusions',
  'fee_challans',
  'fee_payments',
  'fee_late_fee_applications',
  'fee_challan_month_coverage',
  'fee_challan_settings',
  'role_permissions',
  'user_roles',
  'user_branches',
  'id_card_templates',
  'id_cards',
  'id_card_photos',
  'id_card_reprints',
] as const;

/** Has tenant_id column — queried directly. */
export const TENANT_SCOPED_TABLES: readonly { key: string; table: string }[] = [
  { key: 'subscriptions', table: 'subscriptions' },
  { key: 'subscription_invoices', table: 'subscription_invoices' },
] as const;

/** Loaded via subscriptions.id → subscription_id (no tenant_id on table). */
export const SUBSCRIPTION_CHILD_TABLES: readonly { key: string; table: string; fk: string }[] = [
  { key: 'subscription_usage', table: 'subscription_usage', fk: 'subscription_id' },
] as const;
