'use client';

import { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import {
  Box,
  Title,
  TextInput,
  PasswordInput,
  Button,
  Stack,
  Text,
  Anchor,
  Alert,
  Stepper,
  Group,
  Divider,
} from '@mantine/core';
import { useForm } from '@mantine/form';
import {
  IconAlertCircle,
  IconMail,
  IconLock,
  IconUser,
  IconPhone,
  IconCheck,
  IconSchool,
  IconBuilding,
  IconBrandGoogle,
} from '@tabler/icons-react';
import { apiClient, getEffectiveApiBaseURL } from '@/lib/api-client';
import { DEFAULT_THEME_COLOR } from '@/lib/utils/theme';
import { useErrorColor, useInfoColor, useSuccessColor, useNotificationColors } from '@/lib/hooks/use-theme-colors';
import { useTheme } from '@/lib/hooks/use-theme';
import { useThemeColor } from '@/lib/hooks/use-theme-color';
import { generateThemeColors } from '@/lib/utils/themeColors';
import { notifications } from '@mantine/notifications';

interface RegisterData {
  // School/Tenant
  schoolName: string;
  schoolCode: string;
  schoolDomain: string;
  // Branch (branch code is auto-generated by backend)
  branchName: string;
  branchAddress: string;
  branchPhone: string;
  branchEmail: string;
  // Admin User
  email: string;
  password: string;
  confirmPassword: string;
  fullName: string;
  phone: string;
}

type SignupMethod = 'google' | 'email' | null;

export default function SignupPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const errorColor = useErrorColor();
  const infoColor = useInfoColor();
  const successColor = useSuccessColor();
  const notifyColors = useNotificationColors();
  const { isDark } = useTheme();
  const primaryColor = useThemeColor();
  const themeColors = generateThemeColors(primaryColor, isDark);
  const [signupMethod, setSignupMethod] = useState<SignupMethod>(null);
  const [active, setActive] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const form = useForm<RegisterData>({
    initialValues: {
      schoolName: '',
      schoolCode: '',
      schoolDomain: '',
      branchName: '',
      branchAddress: '',
      branchPhone: '',
      branchEmail: '',
      email: '',
      password: '',
      confirmPassword: '',
      fullName: '',
      phone: '',
    },
    validateInputOnBlur: true,
    validateInputOnChange: false,
    validate: {
      schoolName: (value) => (value.length < 2 ? 'School name must be at least 2 characters' : null),
      branchName: (value) => (value.length < 2 ? 'Branch name must be at least 2 characters' : null),
      email: (value) => (/^\S+@\S+$/.test(value) ? null : 'Invalid email'),
      password: (value) => (value.length < 6 ? 'Password must be at least 6 characters' : null),
      confirmPassword: (value, values) =>
        value !== values.password ? 'Passwords do not match' : null,
      fullName: (value) => (value.length < 2 ? 'Full name must be at least 2 characters' : null),
    },
  });

  const nextStep = () => {
    if (active === 0) {
      // Validate step 1: School Information before moving to step 2
      const validation = form.validateField('schoolName');
      if (!validation.hasError) {
        // Clear any errors from other steps when moving forward
        form.clearFieldError('branchName');
        form.clearFieldError('email');
        form.clearFieldError('password');
        form.clearFieldError('confirmPassword');
        form.clearFieldError('fullName');
        setActive((current) => (current < 3 ? current + 1 : current));
      }
    } else if (active === 1) {
      // Validate step 2: Branch Details before moving to step 3
      const validation = form.validateField('branchName');
      if (!validation.hasError) {
        // Clear any errors from other steps when moving forward
        form.clearFieldError('email');
        form.clearFieldError('password');
        form.clearFieldError('confirmPassword');
        form.clearFieldError('fullName');
        setActive((current) => (current < 3 ? current + 1 : current));
      }
    } else if (active === 2) {
      // Validate step 3: Admin Account before moving to step 4
      const fullNameValidation = form.validateField('fullName');

      if (signupMethod === 'google') {
        if (!fullNameValidation.hasError) {
          setActive((current) => (current < 3 ? current + 1 : current));
        }
      } else {
        const emailValidation = form.validateField('email');
        const passwordValidation = form.validateField('password');
        const confirmPasswordValidation = form.validateField('confirmPassword');

        if (
          !emailValidation.hasError &&
          !passwordValidation.hasError &&
          !confirmPasswordValidation.hasError &&
          !fullNameValidation.hasError
        ) {
          setActive((current) => (current < 3 ? current + 1 : current));
        }
      }
    }
  };

  const prevStep = () => {
    // Clear errors when going back
    if (active === 1) {
      form.clearFieldError('branchName');
    } else if (active === 2) {
      form.clearFieldError('email');
      form.clearFieldError('password');
      form.clearFieldError('confirmPassword');
      form.clearFieldError('fullName');
    }
    setActive((current) => (current > 0 ? current - 1 : current));
  };

  const handleGoogleSignup = async (values: RegisterData) => {
    setLoading(true);
    setError(null);

    try {
      const apiBase = getEffectiveApiBaseURL();
      // Encode signup context into a custom query param (gstate), not OAuth state.
      const gstate = btoa(
        JSON.stringify({
          schoolName: values.schoolName,
          branchName: values.branchName,
          fullName: values.fullName,
          phone: values.phone || undefined,
          isSignup: true,
        }),
      );

      window.location.href = `${apiBase}/api/v1/auth/google?gstate=${encodeURIComponent(gstate)}`;
    } catch (err: any) {
      const errorMsg = err.message || 'Failed to initiate Google signup. Please try again.';
      setError(errorMsg);
      setLoading(false);
    }
  };

  const handleSubmit = async (values: RegisterData) => {
    // Email-based signup uses the existing registration endpoint.
    if (signupMethod === 'google') {
      await handleGoogleSignup(values);
      return;
    }

    setLoading(true);
    setError(null);

    try {
      // Call registration API
      const { confirmPassword, ...registerData } = values;
      await apiClient.post('/api/v1/auth/register', {
        schoolName: registerData.schoolName,
        schoolCode: registerData.schoolCode || undefined,
        schoolDomain: registerData.schoolDomain || undefined,
        branchName: registerData.branchName,
        branchAddress: registerData.branchAddress || undefined,
        branchPhone: registerData.branchPhone || undefined,
        branchEmail: registerData.branchEmail || undefined,
        email: registerData.email,
        password: registerData.password,
        fullName: registerData.fullName,
        phone: registerData.phone || undefined,
      });

      // Show success notification briefly, then redirect to login
      notifications.show({
        id: 'signup-success',
        title: 'Account created',
        message: 'Your school account has been created. Redirecting to login…',
        color: notifyColors.success,
        autoClose: 2000,
      });

      setTimeout(() => {
        router.push('/login?registered=true');
      }, 2000);
    } catch (err: any) {
      const errorMsg =
        err.response?.data?.error?.message ||
        err.response?.data?.message ||
        err.message ||
        'Registration failed. Please try again.';
      setError(errorMsg);

      // Show failure notification (stay on page so user can fix and retry)
      notifications.show({
        id: 'signup-error',
        title: 'Registration failed',
        message: errorMsg,
        color: notifyColors.error,
        autoClose: 2000,
      });
    } finally {
      setLoading(false);
    }
  };

  // Prevent implicit submit (e.g. Enter key); only the button should trigger registration
  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
  };

  // Method selection view (Google vs Email) – mirrors RMS signup behaviour.
  if (!signupMethod) {
    return (
      <form id="signup-form" onSubmit={handleFormSubmit}>
        <Stack gap="lg">
          <Box>
            <Title
              order={2}
              size="1.8rem"
              fw={700}
              mb="xs"
              style={{ color: themeColors.colorTextDark }}
            >
              Create Account
            </Title>
            <Text size="sm" style={{ color: themeColors.colorTextMedium }}>
              Choose how you want to sign up for NTG Alma.
            </Text>
          </Box>

          {searchParams.get('google') === 'not_found' && (
            <Alert
              icon={<IconAlertCircle size={16} />}
              style={{
                backgroundColor: `${errorColor}15`,
                borderColor: errorColor,
                color: errorColor,
              }}
              variant="light"
              radius="md"
            >
              <Text size="sm">
                This Google account is not registered. Please sign up below to create your school account.
              </Text>
            </Alert>
          )}

          <Stack gap="md">
            <Button
              id="signup-google-button"
              size="lg"
              radius="md"
              leftSection={<IconBrandGoogle size={20} style={{ color: '#4285F4' }} />}
              onClick={() => setSignupMethod('google')}
              style={{
                backgroundColor: 'white',
                color: '#333333',
                border: '1px solid #e0e0e0',
              }}
              fullWidth
            >
              Sign up with Google
            </Button>

            <Divider label="Or" labelPosition="center" my="md" />

            <Button
              id="signup-email-button"
              size="lg"
              radius="md"
              leftSection={<IconMail size={20} />}
              onClick={() => setSignupMethod('email')}
              style={{
                backgroundColor: DEFAULT_THEME_COLOR,
                color: 'white',
              }}
              fullWidth
            >
              Sign up with email
            </Button>
          </Stack>

          <Text ta="center" size="sm" style={{ color: themeColors.colorTextMedium }}>
            Already have an account?{' '}
            <Anchor
              id="signup-login-link"
              href="/login"
              size="sm"
              style={{ color: DEFAULT_THEME_COLOR, fontWeight: 500 }}
            >
              Sign in
            </Anchor>
          </Text>
        </Stack>
      </form>
    );
  }

  // For now, both Google and email methods use the same multi-step school signup form.
  // Behaviour differences (e.g. redirecting to Google OAuth) can be layered on later.
  return (
    <form id="signup-form" onSubmit={handleFormSubmit}>
      <Stack gap="lg">
        <Box>
          <Button
            id="signup-back-method"
            variant="subtle"
            size="sm"
            onClick={() => {
              setSignupMethod(null);
              setActive(0);
            }}
            style={{ marginBottom: '1rem', color: DEFAULT_THEME_COLOR }}
          >
            Back
          </Button>
          <Title order={2} size="1.8rem" fw={700} mb="xs" style={{ color: themeColors.colorTextDark }}>
            Create School Account
          </Title>
          <Text size="sm" style={{ color: themeColors.colorTextMedium }}>
            Register your school and get started with our management system
          </Text>
        </Box>

        <Stepper active={active} onStepClick={setActive} size="sm">
          <Stepper.Step
            label="School Information"
            description="Basic school details"
            icon={<IconSchool size={18} />}
          >
            <Stack gap="md" mt="xl">
              <TextInput
                id="signup-school-name"
                label="School Name"
                placeholder="Alekaf High School"
                required
                leftSection={<IconSchool size={18} />}
                size="lg"
                radius="md"
                disabled={loading}
                {...form.getInputProps('schoolName')}
              />

              <TextInput
                id="signup-school-code"
                label="School Code (Optional)"
                placeholder="ALEKAF001"
                description="Unique code for your school. Leave empty to auto-generate."
                leftSection={<IconSchool size={18} />}
                size="lg"
                radius="md"
                disabled={loading}
                {...form.getInputProps('schoolCode')}
              />

              <TextInput
                id="signup-school-domain"
                label="Domain (Optional)"
                placeholder="alekaf.edu"
                description="School website domain"
                leftSection={<IconMail size={18} />}
                size="lg"
                radius="md"
                disabled={loading}
                {...form.getInputProps('schoolDomain')}
              />
            </Stack>
          </Stepper.Step>

          <Stepper.Step
            label="Branch Information"
            description="First branch details"
            icon={<IconBuilding size={18} />}
          >
            <Stack gap="md" mt="xl">
              <TextInput
                id="signup-branch-name"
                label="Branch Name"
                placeholder="Main Branch"
                required
                leftSection={<IconBuilding size={18} />}
                size="lg"
                radius="md"
                disabled={loading}
                {...form.getInputProps('branchName')}
              />

              <TextInput
                id="signup-branch-address"
                label="Address (Optional)"
                placeholder="123 School Street, City"
                size="lg"
                radius="md"
                disabled={loading}
                {...form.getInputProps('branchAddress')}
              />

              <Group grow>
                <TextInput
                  id="signup-branch-phone"
                  label="Phone (Optional)"
                  placeholder="+1234567890"
                  leftSection={<IconPhone size={18} />}
                  size="lg"
                  radius="md"
                  disabled={loading}
                  {...form.getInputProps('branchPhone')}
                />

                <TextInput
                id="signup-branch-email"
                label="Email (Optional)"
                placeholder="branch@school.com"
                  leftSection={<IconMail size={18} />}
                  size="lg"
                  radius="md"
                  disabled={loading}
                  {...form.getInputProps('branchEmail')}
                />
              </Group>
            </Stack>
          </Stepper.Step>

          <Stepper.Step
            label="Admin Account"
            description="Create administrator account"
            icon={<IconUser size={18} />}
          >
            <Stack gap="md" mt="xl">
              {signupMethod === 'email' && (
                <TextInput
                  id="signup-email"
                  label="Email"
                  placeholder="admin@school.com"
                  required
                  leftSection={<IconMail size={18} />}
                  size="lg"
                  radius="md"
                  autoComplete="email"
                  disabled={loading}
                  {...form.getInputProps('email')}
                />
              )}

              <TextInput
                id="signup-full-name"
                label="Full Name"
                placeholder="John Doe"
                required
                leftSection={<IconUser size={18} />}
                size="lg"
                radius="md"
                disabled={loading}
                {...form.getInputProps('fullName')}
              />

              <TextInput
                id="signup-phone"
                label="Phone (Optional)"
                placeholder="+1234567890"
                leftSection={<IconPhone size={18} />}
                size="lg"
                radius="md"
                disabled={loading}
                {...form.getInputProps('phone')}
              />

              {signupMethod === 'email' && (
                <>
                  <PasswordInput
                    id="signup-password"
                    label="Password"
                    placeholder="Enter your password"
                    required
                    leftSection={<IconLock size={18} />}
                    size="lg"
                    radius="md"
                    autoComplete="new-password"
                    disabled={loading}
                    {...form.getInputProps('password')}
                  />

                  <PasswordInput
                    id="signup-confirm-password"
                    label="Confirm Password"
                    placeholder="Confirm your password"
                    required
                    leftSection={<IconLock size={18} />}
                    size="lg"
                    radius="md"
                    autoComplete="new-password"
                    disabled={loading}
                    {...form.getInputProps('confirmPassword')}
                  />

                  <Alert
                    style={{
                      backgroundColor: `${infoColor}15`,
                      borderColor: infoColor,
                      color: infoColor,
                    }}
                    variant="light"
                    radius="md"
                  >
                    <Text size="sm">
                      Password must be at least 6 characters long. Choose a strong password to keep your account secure.
                    </Text>
                  </Alert>
                </>
              )}
            </Stack>
          </Stepper.Step>

          <Stepper.Step
            label="Review"
            description="Review your information"
            icon={<IconCheck size={18} />}
          >
            <Stack gap="md" mt="xl">
              <Box>
                <Text size="sm" mb="xs" style={{ color: themeColors.colorTextMedium }}>
                  School Name
                </Text>
                <Text fw={500} style={{ color: themeColors.colorTextDark }}>
                  {form.values.schoolName}
                </Text>
              </Box>

              {form.values.schoolCode && (
                <Box>
                  <Text size="sm" mb="xs" style={{ color: themeColors.colorTextMedium }}>
                    School Code
                  </Text>
                  <Text fw={500} style={{ color: themeColors.colorTextDark }}>
                    {form.values.schoolCode}
                  </Text>
                </Box>
              )}

              <Box>
                <Text size="sm" mb="xs" style={{ color: themeColors.colorTextMedium }}>
                  Branch Name
                </Text>
                <Text fw={500} style={{ color: themeColors.colorTextDark }}>
                  {form.values.branchName}
                </Text>
              </Box>

              <Box>
                <Text size="sm" mb="xs" style={{ color: themeColors.colorTextMedium }}>
                  Admin Name
                </Text>
                <Text fw={500} style={{ color: themeColors.colorTextDark }}>
                  {form.values.fullName}
                </Text>
              </Box>

              {error && (
                <Alert
                  icon={<IconAlertCircle size={16} />}
                  style={{
                    backgroundColor: `${errorColor}15`,
                    borderColor: errorColor,
                    color: errorColor,
                  }}
                  variant="light"
                  radius="md"
                >
                  {error}
                </Alert>
              )}
            </Stack>
          </Stepper.Step>

          <Stepper.Completed>
            <Stack gap="md" mt="xl">
              <Alert
                style={{
                  backgroundColor: `${successColor}15`,
                  borderColor: successColor,
                  color: successColor,
                }}
                variant="light"
                radius="md"
              >
                <Text size="sm" fw={500}>
                  Account created successfully! Redirecting...
                </Text>
              </Alert>
            </Stack>
          </Stepper.Completed>
        </Stepper>

        <Group justify="space-between" mt="xl">
          {active > 0 ? (
            <Button
              id="signup-prev"
              type="button"
              variant="default"
              onClick={prevStep}
              disabled={loading}
              style={{
                backgroundColor: isDark ? themeColors.colorMedium : '#f5f5f5',
                color: themeColors.colorTextDark,
                borderColor: themeColors.borderLight,
              }}
            >
              Previous
            </Button>
          ) : (
            <div /> // Spacer
          )}
          {active < 3 ? (
            <Button
              id="signup-next"
              type="button"
              onClick={nextStep}
              disabled={loading}
              style={{
                backgroundColor: DEFAULT_THEME_COLOR,
                color: 'white',
              }}
            >
              Next
            </Button>
          ) : (
            <Button
              id="signup-submit"
              type="button"
              loading={loading}
              onClick={() => {
                if (signupMethod === 'google') {
                  // For Google signup, go straight to Google OAuth without hitting the email/password validator.
                  void handleGoogleSignup(form.values);
                } else {
                  form.onSubmit(handleSubmit)();
                }
              }}
              style={{
                backgroundColor: signupMethod === 'google' ? 'white' : DEFAULT_THEME_COLOR,
                color: signupMethod === 'google' ? '#333333' : 'white',
                border: signupMethod === 'google' ? '1px solid #e0e0e0' : undefined,
              }}
            >
              {signupMethod === 'google' ? 'Continue with Google' : 'Create Account'}
            </Button>
          )}
        </Group>

        <Text ta="center" size="sm" style={{ color: themeColors.colorTextMedium }}>
          Already have an account?{' '}
          <Anchor id="signup-signin-link" href="/login" size="sm" style={{ color: DEFAULT_THEME_COLOR, fontWeight: 500 }}>
            Sign in
          </Anchor>
        </Text>
      </Stack>
    </form>
  );
}

